`toString` now works with null keys or values
Fixed exception 
TypeError: Cannot read property `toString` of null 
when calling toString and key or value is null.